'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceRefSinFechaHora
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://siat.impuestos.gob.bo/", ConfigurationName:="ServiceRefSinFechaHora.IServicioSincronizacionFechaHora")>  _
    Public Interface IServicioSincronizacionFechaHora
        
        'CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function verificarComunicacion(ByVal request As ServiceRefSinFechaHora.verificarComunicacion) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceRefSinFechaHora.verificarComunicacionResponse
        
        'CODEGEN: El parámetro 'RespuestaFechaHora' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function sincronizarFechaHora(ByVal request As ServiceRefSinFechaHora.sincronizarFechaHora) As <System.ServiceModel.MessageParameterAttribute(Name:="RespuestaFechaHora")> ServiceRefSinFechaHora.sincronizarFechaHoraResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="verificarComunicacion", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class verificarComunicacion
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="verificarComunicacionResponse", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class verificarComunicacionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://siat.impuestos.gob.bo/")>  _
    Partial Public Class solicitudSincronizacion
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoAmbienteField As Integer
        
        Private codigoPuntoVentaField As System.Nullable(Of Integer)
        
        Private codigoPuntoVentaFieldSpecified As Boolean
        
        Private codigoSistemaField As String
        
        Private codigoSucursalField As Integer
        
        Private cuisField As String
        
        Private nitField As Long
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codigoAmbiente() As Integer
            Get
                Return Me.codigoAmbienteField
            End Get
            Set
                Me.codigoAmbienteField = value
                Me.RaisePropertyChanged("codigoAmbiente")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property codigoPuntoVenta() As System.Nullable(Of Integer)
            Get
                Return Me.codigoPuntoVentaField
            End Get
            Set
                Me.codigoPuntoVentaField = value
                Me.RaisePropertyChanged("codigoPuntoVenta")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property codigoPuntoVentaSpecified() As Boolean
            Get
                Return Me.codigoPuntoVentaFieldSpecified
            End Get
            Set
                Me.codigoPuntoVentaFieldSpecified = value
                Me.RaisePropertyChanged("codigoPuntoVentaSpecified")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property codigoSistema() As String
            Get
                Return Me.codigoSistemaField
            End Get
            Set
                Me.codigoSistemaField = value
                Me.RaisePropertyChanged("codigoSistema")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property codigoSucursal() As Integer
            Get
                Return Me.codigoSucursalField
            End Get
            Set
                Me.codigoSucursalField = value
                Me.RaisePropertyChanged("codigoSucursal")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property cuis() As String
            Get
                Return Me.cuisField
            End Get
            Set
                Me.cuisField = value
                Me.RaisePropertyChanged("cuis")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property nit() As Long
            Get
                Return Me.nitField
            End Get
            Set
                Me.nitField = value
                Me.RaisePropertyChanged("nit")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://siat.impuestos.gob.bo/")>  _
    Partial Public Class respuestaCodigosMensajesSoapDto
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoMensajeField As Integer
        
        Private codigoMensajeFieldSpecified As Boolean
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codigoMensaje() As Integer
            Get
                Return Me.codigoMensajeField
            End Get
            Set
                Me.codigoMensajeField = value
                Me.RaisePropertyChanged("codigoMensaje")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property codigoMensajeSpecified() As Boolean
            Get
                Return Me.codigoMensajeFieldSpecified
            End Get
            Set
                Me.codigoMensajeFieldSpecified = value
                Me.RaisePropertyChanged("codigoMensajeSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://siat.impuestos.gob.bo/")>  _
    Partial Public Class respuestaFechaHora
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private fechaHoraField As String
        
        Private listaCodigosRespuestasField() As respuestaCodigosMensajesSoapDto
        
        Private transaccionField As Boolean
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property fechaHora() As String
            Get
                Return Me.fechaHoraField
            End Get
            Set
                Me.fechaHoraField = value
                Me.RaisePropertyChanged("fechaHora")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("listaCodigosRespuestas", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property listaCodigosRespuestas() As respuestaCodigosMensajesSoapDto()
            Get
                Return Me.listaCodigosRespuestasField
            End Get
            Set
                Me.listaCodigosRespuestasField = value
                Me.RaisePropertyChanged("listaCodigosRespuestas")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property transaccion() As Boolean
            Get
                Return Me.transaccionField
            End Get
            Set
                Me.transaccionField = value
                Me.RaisePropertyChanged("transaccion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sincronizarFechaHora", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class sincronizarFechaHora
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public SolicitudSincronizacion As ServiceRefSinFechaHora.solicitudSincronizacion
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SolicitudSincronizacion As ServiceRefSinFechaHora.solicitudSincronizacion)
            MyBase.New
            Me.SolicitudSincronizacion = SolicitudSincronizacion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sincronizarFechaHoraResponse", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class sincronizarFechaHoraResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public RespuestaFechaHora As ServiceRefSinFechaHora.respuestaFechaHora
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RespuestaFechaHora As ServiceRefSinFechaHora.respuestaFechaHora)
            MyBase.New
            Me.RespuestaFechaHora = RespuestaFechaHora
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServicioSincronizacionFechaHoraChannel
        Inherits ServiceRefSinFechaHora.IServicioSincronizacionFechaHora, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServicioSincronizacionFechaHoraClient
        Inherits System.ServiceModel.ClientBase(Of ServiceRefSinFechaHora.IServicioSincronizacionFechaHora)
        Implements ServiceRefSinFechaHora.IServicioSincronizacionFechaHora
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceRefSinFechaHora_IServicioSincronizacionFechaHora_verificarComunicacion(ByVal request As ServiceRefSinFechaHora.verificarComunicacion) As ServiceRefSinFechaHora.verificarComunicacionResponse Implements ServiceRefSinFechaHora.IServicioSincronizacionFechaHora.verificarComunicacion
            Return MyBase.Channel.verificarComunicacion(request)
        End Function
        
        Public Function verificarComunicacion() As Integer
            Dim inValue As ServiceRefSinFechaHora.verificarComunicacion = New ServiceRefSinFechaHora.verificarComunicacion()
            Dim retVal As ServiceRefSinFechaHora.verificarComunicacionResponse = CType(Me,ServiceRefSinFechaHora.IServicioSincronizacionFechaHora).verificarComunicacion(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceRefSinFechaHora_IServicioSincronizacionFechaHora_sincronizarFechaHora(ByVal request As ServiceRefSinFechaHora.sincronizarFechaHora) As ServiceRefSinFechaHora.sincronizarFechaHoraResponse Implements ServiceRefSinFechaHora.IServicioSincronizacionFechaHora.sincronizarFechaHora
            Return MyBase.Channel.sincronizarFechaHora(request)
        End Function
        
        Public Function sincronizarFechaHora(ByVal SolicitudSincronizacion As ServiceRefSinFechaHora.solicitudSincronizacion) As ServiceRefSinFechaHora.respuestaFechaHora
            Dim inValue As ServiceRefSinFechaHora.sincronizarFechaHora = New ServiceRefSinFechaHora.sincronizarFechaHora()
            inValue.SolicitudSincronizacion = SolicitudSincronizacion
            Dim retVal As ServiceRefSinFechaHora.sincronizarFechaHoraResponse = CType(Me,ServiceRefSinFechaHora.IServicioSincronizacionFechaHora).sincronizarFechaHora(inValue)
            Return retVal.RespuestaFechaHora
        End Function
    End Class
End Namespace
