'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceRefFEstandar
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://siat.impuestos.gob.bo/", ConfigurationName:="ServiceRefFEstandar.IServicioFacturaElectronicaEstandar")>  _
    Public Interface IServicioFacturaElectronicaEstandar
        
        'CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function recepcionPaqueteFacturaElectronicaEstandar(ByVal request As ServiceRefFEstandar.recepcionPaqueteFacturaElectronicaEstandar) As <System.ServiceModel.MessageParameterAttribute(Name:="RespuestaServicioFacturacion")> ServiceRefFEstandar.recepcionPaqueteFacturaElectronicaEstandarResponse
        
        'CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function verificarComunicacion(ByVal request As ServiceRefFEstandar.verificarComunicacion) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceRefFEstandar.verificarComunicacionResponse
        
        'CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function validacionAnulacionFacturaElectronicaEstandar(ByVal request As ServiceRefFEstandar.validacionAnulacionFacturaElectronicaEstandar) As <System.ServiceModel.MessageParameterAttribute(Name:="RespuestaServicioFacturacion")> ServiceRefFEstandar.validacionAnulacionFacturaElectronicaEstandarResponse
        
        'CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function validacionRecepcionFacturaElectronicaEstandar(ByVal request As ServiceRefFEstandar.validacionRecepcionFacturaElectronicaEstandar) As <System.ServiceModel.MessageParameterAttribute(Name:="RespuestaServicioFacturacion")> ServiceRefFEstandar.validacionRecepcionFacturaElectronicaEstandarResponse
        
        'CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function recepcionFacturaElectronicaEstandar(ByVal request As ServiceRefFEstandar.recepcionFacturaElectronicaEstandar) As <System.ServiceModel.MessageParameterAttribute(Name:="RespuestaServicioFacturacion")> ServiceRefFEstandar.recepcionFacturaElectronicaEstandarResponse
        
        'CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function anulacionFacturaElectronicaEstandar(ByVal request As ServiceRefFEstandar.anulacionFacturaElectronicaEstandar) As <System.ServiceModel.MessageParameterAttribute(Name:="RespuestaServicioFacturacion")> ServiceRefFEstandar.anulacionFacturaElectronicaEstandarResponse
        
        'CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function validacionRecepcionPaqueteFacturaElectronicaEstandar(ByVal request As ServiceRefFEstandar.validacionRecepcionPaqueteFacturaElectronicaEstandar) As <System.ServiceModel.MessageParameterAttribute(Name:="RespuestaServicioFacturacion")> ServiceRefFEstandar.validacionRecepcionPaqueteFacturaElectronicaEstandarResponse
    End Interface
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://siat.impuestos.gob.bo/")>  _
    Partial Public Class solicitudRecepcion
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private archivoField As String
        
        Private codigoAmbienteField As Integer
        
        Private codigoDocumentoFiscalField As Integer
        
        Private codigoDocumentoSectorField As Integer
        
        Private codigoEmisionField As Integer
        
        Private codigoModalidadField As Integer
        
        Private codigoPuntoVentaField As System.Nullable(Of Integer)
        
        Private codigoPuntoVentaFieldSpecified As Boolean
        
        Private codigoSistemaField As String
        
        Private codigoSucursalField As Integer
        
        Private cufdField As String
        
        Private cuisField As String
        
        Private fechaEnvioField As Date
        
        Private hashArchivoField As String
        
        Private nitField As Long
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property archivo() As String
            Get
                Return Me.archivoField
            End Get
            Set
                Me.archivoField = value
                Me.RaisePropertyChanged("archivo")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property codigoAmbiente() As Integer
            Get
                Return Me.codigoAmbienteField
            End Get
            Set
                Me.codigoAmbienteField = value
                Me.RaisePropertyChanged("codigoAmbiente")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property codigoDocumentoFiscal() As Integer
            Get
                Return Me.codigoDocumentoFiscalField
            End Get
            Set
                Me.codigoDocumentoFiscalField = value
                Me.RaisePropertyChanged("codigoDocumentoFiscal")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property codigoDocumentoSector() As Integer
            Get
                Return Me.codigoDocumentoSectorField
            End Get
            Set
                Me.codigoDocumentoSectorField = value
                Me.RaisePropertyChanged("codigoDocumentoSector")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property codigoEmision() As Integer
            Get
                Return Me.codigoEmisionField
            End Get
            Set
                Me.codigoEmisionField = value
                Me.RaisePropertyChanged("codigoEmision")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property codigoModalidad() As Integer
            Get
                Return Me.codigoModalidadField
            End Get
            Set
                Me.codigoModalidadField = value
                Me.RaisePropertyChanged("codigoModalidad")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=6)>  _
        Public Property codigoPuntoVenta() As System.Nullable(Of Integer)
            Get
                Return Me.codigoPuntoVentaField
            End Get
            Set
                Me.codigoPuntoVentaField = value
                Me.RaisePropertyChanged("codigoPuntoVenta")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property codigoPuntoVentaSpecified() As Boolean
            Get
                Return Me.codigoPuntoVentaFieldSpecified
            End Get
            Set
                Me.codigoPuntoVentaFieldSpecified = value
                Me.RaisePropertyChanged("codigoPuntoVentaSpecified")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property codigoSistema() As String
            Get
                Return Me.codigoSistemaField
            End Get
            Set
                Me.codigoSistemaField = value
                Me.RaisePropertyChanged("codigoSistema")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property codigoSucursal() As Integer
            Get
                Return Me.codigoSucursalField
            End Get
            Set
                Me.codigoSucursalField = value
                Me.RaisePropertyChanged("codigoSucursal")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property cufd() As String
            Get
                Return Me.cufdField
            End Get
            Set
                Me.cufdField = value
                Me.RaisePropertyChanged("cufd")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property cuis() As String
            Get
                Return Me.cuisField
            End Get
            Set
                Me.cuisField = value
                Me.RaisePropertyChanged("cuis")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property fechaEnvio() As Date
            Get
                Return Me.fechaEnvioField
            End Get
            Set
                Me.fechaEnvioField = value
                Me.RaisePropertyChanged("fechaEnvio")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property hashArchivo() As String
            Get
                Return Me.hashArchivoField
            End Get
            Set
                Me.hashArchivoField = value
                Me.RaisePropertyChanged("hashArchivo")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property nit() As Long
            Get
                Return Me.nitField
            End Get
            Set
                Me.nitField = value
                Me.RaisePropertyChanged("nit")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://siat.impuestos.gob.bo/")>  _
    Partial Public Class solicitudAnulacion
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoAmbienteField As Integer
        
        Private codigoDocumentoFiscalField As Integer
        
        Private codigoDocumentoSectorField As Integer
        
        Private codigoEmisionField As Integer
        
        Private codigoModalidadField As Integer
        
        Private codigoMotivoField As Integer
        
        Private codigoPuntoVentaField As System.Nullable(Of Integer)
        
        Private codigoPuntoVentaFieldSpecified As Boolean
        
        Private codigoSistemaField As String
        
        Private codigoSucursalField As Integer
        
        Private cufField As String
        
        Private cufdField As String
        
        Private cuisField As String
        
        Private nitField As Long
        
        Private numeroDocumentoFiscalField As Long
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codigoAmbiente() As Integer
            Get
                Return Me.codigoAmbienteField
            End Get
            Set
                Me.codigoAmbienteField = value
                Me.RaisePropertyChanged("codigoAmbiente")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property codigoDocumentoFiscal() As Integer
            Get
                Return Me.codigoDocumentoFiscalField
            End Get
            Set
                Me.codigoDocumentoFiscalField = value
                Me.RaisePropertyChanged("codigoDocumentoFiscal")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property codigoDocumentoSector() As Integer
            Get
                Return Me.codigoDocumentoSectorField
            End Get
            Set
                Me.codigoDocumentoSectorField = value
                Me.RaisePropertyChanged("codigoDocumentoSector")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property codigoEmision() As Integer
            Get
                Return Me.codigoEmisionField
            End Get
            Set
                Me.codigoEmisionField = value
                Me.RaisePropertyChanged("codigoEmision")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property codigoModalidad() As Integer
            Get
                Return Me.codigoModalidadField
            End Get
            Set
                Me.codigoModalidadField = value
                Me.RaisePropertyChanged("codigoModalidad")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property codigoMotivo() As Integer
            Get
                Return Me.codigoMotivoField
            End Get
            Set
                Me.codigoMotivoField = value
                Me.RaisePropertyChanged("codigoMotivo")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=6)>  _
        Public Property codigoPuntoVenta() As System.Nullable(Of Integer)
            Get
                Return Me.codigoPuntoVentaField
            End Get
            Set
                Me.codigoPuntoVentaField = value
                Me.RaisePropertyChanged("codigoPuntoVenta")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property codigoPuntoVentaSpecified() As Boolean
            Get
                Return Me.codigoPuntoVentaFieldSpecified
            End Get
            Set
                Me.codigoPuntoVentaFieldSpecified = value
                Me.RaisePropertyChanged("codigoPuntoVentaSpecified")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property codigoSistema() As String
            Get
                Return Me.codigoSistemaField
            End Get
            Set
                Me.codigoSistemaField = value
                Me.RaisePropertyChanged("codigoSistema")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property codigoSucursal() As Integer
            Get
                Return Me.codigoSucursalField
            End Get
            Set
                Me.codigoSucursalField = value
                Me.RaisePropertyChanged("codigoSucursal")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property cuf() As String
            Get
                Return Me.cufField
            End Get
            Set
                Me.cufField = value
                Me.RaisePropertyChanged("cuf")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property cufd() As String
            Get
                Return Me.cufdField
            End Get
            Set
                Me.cufdField = value
                Me.RaisePropertyChanged("cufd")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property cuis() As String
            Get
                Return Me.cuisField
            End Get
            Set
                Me.cuisField = value
                Me.RaisePropertyChanged("cuis")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property nit() As Long
            Get
                Return Me.nitField
            End Get
            Set
                Me.nitField = value
                Me.RaisePropertyChanged("nit")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property numeroDocumentoFiscal() As Long
            Get
                Return Me.numeroDocumentoFiscalField
            End Get
            Set
                Me.numeroDocumentoFiscalField = value
                Me.RaisePropertyChanged("numeroDocumentoFiscal")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://siat.impuestos.gob.bo/")>  _
    Partial Public Class solicitudValidacionRecepcion
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoAmbienteField As Integer
        
        Private codigoDocumentoFiscalField As Integer
        
        Private codigoDocumentoSectorField As Integer
        
        Private codigoEmisionField As Integer
        
        Private codigoModalidadField As Integer
        
        Private codigoPuntoVentaField As System.Nullable(Of Integer)
        
        Private codigoPuntoVentaFieldSpecified As Boolean
        
        Private codigoRecepcionField As Long
        
        Private codigoSistemaField As String
        
        Private codigoSucursalField As Integer
        
        Private cufdField As String
        
        Private cuisField As String
        
        Private nitField As Long
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codigoAmbiente() As Integer
            Get
                Return Me.codigoAmbienteField
            End Get
            Set
                Me.codigoAmbienteField = value
                Me.RaisePropertyChanged("codigoAmbiente")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property codigoDocumentoFiscal() As Integer
            Get
                Return Me.codigoDocumentoFiscalField
            End Get
            Set
                Me.codigoDocumentoFiscalField = value
                Me.RaisePropertyChanged("codigoDocumentoFiscal")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property codigoDocumentoSector() As Integer
            Get
                Return Me.codigoDocumentoSectorField
            End Get
            Set
                Me.codigoDocumentoSectorField = value
                Me.RaisePropertyChanged("codigoDocumentoSector")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property codigoEmision() As Integer
            Get
                Return Me.codigoEmisionField
            End Get
            Set
                Me.codigoEmisionField = value
                Me.RaisePropertyChanged("codigoEmision")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property codigoModalidad() As Integer
            Get
                Return Me.codigoModalidadField
            End Get
            Set
                Me.codigoModalidadField = value
                Me.RaisePropertyChanged("codigoModalidad")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=5)>  _
        Public Property codigoPuntoVenta() As System.Nullable(Of Integer)
            Get
                Return Me.codigoPuntoVentaField
            End Get
            Set
                Me.codigoPuntoVentaField = value
                Me.RaisePropertyChanged("codigoPuntoVenta")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property codigoPuntoVentaSpecified() As Boolean
            Get
                Return Me.codigoPuntoVentaFieldSpecified
            End Get
            Set
                Me.codigoPuntoVentaFieldSpecified = value
                Me.RaisePropertyChanged("codigoPuntoVentaSpecified")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property codigoRecepcion() As Long
            Get
                Return Me.codigoRecepcionField
            End Get
            Set
                Me.codigoRecepcionField = value
                Me.RaisePropertyChanged("codigoRecepcion")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property codigoSistema() As String
            Get
                Return Me.codigoSistemaField
            End Get
            Set
                Me.codigoSistemaField = value
                Me.RaisePropertyChanged("codigoSistema")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property codigoSucursal() As Integer
            Get
                Return Me.codigoSucursalField
            End Get
            Set
                Me.codigoSucursalField = value
                Me.RaisePropertyChanged("codigoSucursal")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property cufd() As String
            Get
                Return Me.cufdField
            End Get
            Set
                Me.cufdField = value
                Me.RaisePropertyChanged("cufd")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property cuis() As String
            Get
                Return Me.cuisField
            End Get
            Set
                Me.cuisField = value
                Me.RaisePropertyChanged("cuis")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property nit() As Long
            Get
                Return Me.nitField
            End Get
            Set
                Me.nitField = value
                Me.RaisePropertyChanged("nit")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://siat.impuestos.gob.bo/")>  _
    Partial Public Class solicitudValidacionAnulacion
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoAmbienteField As Integer
        
        Private codigoDocumentoFiscalField As Integer
        
        Private codigoDocumentoSectorField As Integer
        
        Private codigoEmisionField As Integer
        
        Private codigoModalidadField As Integer
        
        Private codigoMotivoField As Integer
        
        Private codigoPuntoVentaField As System.Nullable(Of Integer)
        
        Private codigoPuntoVentaFieldSpecified As Boolean
        
        Private codigoRecepcionField As Long
        
        Private codigoSistemaField As String
        
        Private codigoSucursalField As Integer
        
        Private cufField As String
        
        Private cufdField As String
        
        Private cuisField As String
        
        Private nitField As Long
        
        Private numeroDocumentoFiscalField As Long
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codigoAmbiente() As Integer
            Get
                Return Me.codigoAmbienteField
            End Get
            Set
                Me.codigoAmbienteField = value
                Me.RaisePropertyChanged("codigoAmbiente")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property codigoDocumentoFiscal() As Integer
            Get
                Return Me.codigoDocumentoFiscalField
            End Get
            Set
                Me.codigoDocumentoFiscalField = value
                Me.RaisePropertyChanged("codigoDocumentoFiscal")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property codigoDocumentoSector() As Integer
            Get
                Return Me.codigoDocumentoSectorField
            End Get
            Set
                Me.codigoDocumentoSectorField = value
                Me.RaisePropertyChanged("codigoDocumentoSector")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property codigoEmision() As Integer
            Get
                Return Me.codigoEmisionField
            End Get
            Set
                Me.codigoEmisionField = value
                Me.RaisePropertyChanged("codigoEmision")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property codigoModalidad() As Integer
            Get
                Return Me.codigoModalidadField
            End Get
            Set
                Me.codigoModalidadField = value
                Me.RaisePropertyChanged("codigoModalidad")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property codigoMotivo() As Integer
            Get
                Return Me.codigoMotivoField
            End Get
            Set
                Me.codigoMotivoField = value
                Me.RaisePropertyChanged("codigoMotivo")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=6)>  _
        Public Property codigoPuntoVenta() As System.Nullable(Of Integer)
            Get
                Return Me.codigoPuntoVentaField
            End Get
            Set
                Me.codigoPuntoVentaField = value
                Me.RaisePropertyChanged("codigoPuntoVenta")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property codigoPuntoVentaSpecified() As Boolean
            Get
                Return Me.codigoPuntoVentaFieldSpecified
            End Get
            Set
                Me.codigoPuntoVentaFieldSpecified = value
                Me.RaisePropertyChanged("codigoPuntoVentaSpecified")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property codigoRecepcion() As Long
            Get
                Return Me.codigoRecepcionField
            End Get
            Set
                Me.codigoRecepcionField = value
                Me.RaisePropertyChanged("codigoRecepcion")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property codigoSistema() As String
            Get
                Return Me.codigoSistemaField
            End Get
            Set
                Me.codigoSistemaField = value
                Me.RaisePropertyChanged("codigoSistema")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property codigoSucursal() As Integer
            Get
                Return Me.codigoSucursalField
            End Get
            Set
                Me.codigoSucursalField = value
                Me.RaisePropertyChanged("codigoSucursal")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property cuf() As String
            Get
                Return Me.cufField
            End Get
            Set
                Me.cufField = value
                Me.RaisePropertyChanged("cuf")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property cufd() As String
            Get
                Return Me.cufdField
            End Get
            Set
                Me.cufdField = value
                Me.RaisePropertyChanged("cufd")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property cuis() As String
            Get
                Return Me.cuisField
            End Get
            Set
                Me.cuisField = value
                Me.RaisePropertyChanged("cuis")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property nit() As Long
            Get
                Return Me.nitField
            End Get
            Set
                Me.nitField = value
                Me.RaisePropertyChanged("nit")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=14)>  _
        Public Property numeroDocumentoFiscal() As Long
            Get
                Return Me.numeroDocumentoFiscalField
            End Get
            Set
                Me.numeroDocumentoFiscalField = value
                Me.RaisePropertyChanged("numeroDocumentoFiscal")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://siat.impuestos.gob.bo/")>  _
    Partial Public Class recepcionErrorDetalleDto
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoRecepcionIndividualField As Long
        
        Private cufField As String
        
        Private listaCodigosErrorField() As System.Nullable(Of Integer)
        
        Private numeroFacturaField As Long
        
        Private numeroFacturaFieldSpecified As Boolean
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codigoRecepcionIndividual() As Long
            Get
                Return Me.codigoRecepcionIndividualField
            End Get
            Set
                Me.codigoRecepcionIndividualField = value
                Me.RaisePropertyChanged("codigoRecepcionIndividual")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property cuf() As String
            Get
                Return Me.cufField
            End Get
            Set
                Me.cufField = value
                Me.RaisePropertyChanged("cuf")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("listaCodigosError", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property listaCodigosError() As System.Nullable(Of Integer)()
            Get
                Return Me.listaCodigosErrorField
            End Get
            Set
                Me.listaCodigosErrorField = value
                Me.RaisePropertyChanged("listaCodigosError")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property numeroFactura() As Long
            Get
                Return Me.numeroFacturaField
            End Get
            Set
                Me.numeroFacturaField = value
                Me.RaisePropertyChanged("numeroFactura")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property numeroFacturaSpecified() As Boolean
            Get
                Return Me.numeroFacturaFieldSpecified
            End Get
            Set
                Me.numeroFacturaFieldSpecified = value
                Me.RaisePropertyChanged("numeroFacturaSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://siat.impuestos.gob.bo/")>  _
    Partial Public Class respuesta
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoEstadoField As Integer
        
        Private codigoRecepcionField As Long
        
        Private listaCodigosRespuestasField() As System.Nullable(Of Integer)
        
        Private listaDescripcionesRespuestasField() As String
        
        Private listaErroresDetallesField() As recepcionErrorDetalleDto
        
        Private transaccionField As Boolean
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codigoEstado() As Integer
            Get
                Return Me.codigoEstadoField
            End Get
            Set
                Me.codigoEstadoField = value
                Me.RaisePropertyChanged("codigoEstado")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property codigoRecepcion() As Long
            Get
                Return Me.codigoRecepcionField
            End Get
            Set
                Me.codigoRecepcionField = value
                Me.RaisePropertyChanged("codigoRecepcion")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("listaCodigosRespuestas", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property listaCodigosRespuestas() As System.Nullable(Of Integer)()
            Get
                Return Me.listaCodigosRespuestasField
            End Get
            Set
                Me.listaCodigosRespuestasField = value
                Me.RaisePropertyChanged("listaCodigosRespuestas")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("listaDescripcionesRespuestas", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3)>  _
        Public Property listaDescripcionesRespuestas() As String()
            Get
                Return Me.listaDescripcionesRespuestasField
            End Get
            Set
                Me.listaDescripcionesRespuestasField = value
                Me.RaisePropertyChanged("listaDescripcionesRespuestas")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("listaErroresDetalles", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=4)>  _
        Public Property listaErroresDetalles() As recepcionErrorDetalleDto()
            Get
                Return Me.listaErroresDetallesField
            End Get
            Set
                Me.listaErroresDetallesField = value
                Me.RaisePropertyChanged("listaErroresDetalles")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property transaccion() As Boolean
            Get
                Return Me.transaccionField
            End Get
            Set
                Me.transaccionField = value
                Me.RaisePropertyChanged("transaccion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="recepcionPaqueteFacturaElectronicaEstandar", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class recepcionPaqueteFacturaElectronicaEstandar
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public SolicitudServicioRecepcion As ServiceRefFEstandar.solicitudRecepcion
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SolicitudServicioRecepcion As ServiceRefFEstandar.solicitudRecepcion)
            MyBase.New
            Me.SolicitudServicioRecepcion = SolicitudServicioRecepcion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="recepcionPaqueteFacturaElectronicaEstandarResponse", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class recepcionPaqueteFacturaElectronicaEstandarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public RespuestaServicioFacturacion As ServiceRefFEstandar.respuesta
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RespuestaServicioFacturacion As ServiceRefFEstandar.respuesta)
            MyBase.New
            Me.RespuestaServicioFacturacion = RespuestaServicioFacturacion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="verificarComunicacion", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class verificarComunicacion
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="verificarComunicacionResponse", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class verificarComunicacionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="validacionAnulacionFacturaElectronicaEstandar", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class validacionAnulacionFacturaElectronicaEstandar
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public SolicitudServicioValidacionAnulacion As ServiceRefFEstandar.solicitudValidacionAnulacion
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SolicitudServicioValidacionAnulacion As ServiceRefFEstandar.solicitudValidacionAnulacion)
            MyBase.New
            Me.SolicitudServicioValidacionAnulacion = SolicitudServicioValidacionAnulacion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="validacionAnulacionFacturaElectronicaEstandarResponse", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class validacionAnulacionFacturaElectronicaEstandarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public RespuestaServicioFacturacion As ServiceRefFEstandar.respuesta
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RespuestaServicioFacturacion As ServiceRefFEstandar.respuesta)
            MyBase.New
            Me.RespuestaServicioFacturacion = RespuestaServicioFacturacion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="validacionRecepcionFacturaElectronicaEstandar", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class validacionRecepcionFacturaElectronicaEstandar
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public SolicitudServicioValidacionRecepcion As ServiceRefFEstandar.solicitudValidacionRecepcion
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SolicitudServicioValidacionRecepcion As ServiceRefFEstandar.solicitudValidacionRecepcion)
            MyBase.New
            Me.SolicitudServicioValidacionRecepcion = SolicitudServicioValidacionRecepcion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="validacionRecepcionFacturaElectronicaEstandarResponse", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class validacionRecepcionFacturaElectronicaEstandarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public RespuestaServicioFacturacion As ServiceRefFEstandar.respuesta
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RespuestaServicioFacturacion As ServiceRefFEstandar.respuesta)
            MyBase.New
            Me.RespuestaServicioFacturacion = RespuestaServicioFacturacion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="recepcionFacturaElectronicaEstandar", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class recepcionFacturaElectronicaEstandar
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public SolicitudServicioRecepcion As ServiceRefFEstandar.solicitudRecepcion
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SolicitudServicioRecepcion As ServiceRefFEstandar.solicitudRecepcion)
            MyBase.New
            Me.SolicitudServicioRecepcion = SolicitudServicioRecepcion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="recepcionFacturaElectronicaEstandarResponse", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class recepcionFacturaElectronicaEstandarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public RespuestaServicioFacturacion As ServiceRefFEstandar.respuesta
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RespuestaServicioFacturacion As ServiceRefFEstandar.respuesta)
            MyBase.New
            Me.RespuestaServicioFacturacion = RespuestaServicioFacturacion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="anulacionFacturaElectronicaEstandar", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class anulacionFacturaElectronicaEstandar
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public SolicitudServicioAnulacion As ServiceRefFEstandar.solicitudAnulacion
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SolicitudServicioAnulacion As ServiceRefFEstandar.solicitudAnulacion)
            MyBase.New
            Me.SolicitudServicioAnulacion = SolicitudServicioAnulacion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="anulacionFacturaElectronicaEstandarResponse", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class anulacionFacturaElectronicaEstandarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public RespuestaServicioFacturacion As ServiceRefFEstandar.respuesta
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RespuestaServicioFacturacion As ServiceRefFEstandar.respuesta)
            MyBase.New
            Me.RespuestaServicioFacturacion = RespuestaServicioFacturacion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="validacionRecepcionPaqueteFacturaElectronicaEstandar", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class validacionRecepcionPaqueteFacturaElectronicaEstandar
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public SolicitudServicioValidacionRecepcion As ServiceRefFEstandar.solicitudValidacionRecepcion
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SolicitudServicioValidacionRecepcion As ServiceRefFEstandar.solicitudValidacionRecepcion)
            MyBase.New
            Me.SolicitudServicioValidacionRecepcion = SolicitudServicioValidacionRecepcion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="validacionRecepcionPaqueteFacturaElectronicaEstandarResponse", WrapperNamespace:="https://siat.impuestos.gob.bo/", IsWrapped:=true)>  _
    Partial Public Class validacionRecepcionPaqueteFacturaElectronicaEstandarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://siat.impuestos.gob.bo/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public RespuestaServicioFacturacion As ServiceRefFEstandar.respuesta
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RespuestaServicioFacturacion As ServiceRefFEstandar.respuesta)
            MyBase.New
            Me.RespuestaServicioFacturacion = RespuestaServicioFacturacion
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServicioFacturaElectronicaEstandarChannel
        Inherits ServiceRefFEstandar.IServicioFacturaElectronicaEstandar, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")> _
    Partial Public Class ServicioFacturaElectronicaEstandarClient
        Inherits System.ServiceModel.ClientBase(Of ServiceRefFEstandar.IServicioFacturaElectronicaEstandar)
        Implements ServiceRefFEstandar.IServicioFacturaElectronicaEstandar

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ServiceRefFEstandar_IServicioFacturaElectronicaEstandar_recepcionPaqueteFacturaElectronicaEstandar(ByVal request As ServiceRefFEstandar.recepcionPaqueteFacturaElectronicaEstandar) As ServiceRefFEstandar.recepcionPaqueteFacturaElectronicaEstandarResponse Implements ServiceRefFEstandar.IServicioFacturaElectronicaEstandar.recepcionPaqueteFacturaElectronicaEstandar
            Return MyBase.Channel.recepcionPaqueteFacturaElectronicaEstandar(request)
        End Function

        Public Function recepcionPaqueteFacturaElectronicaEstandar(ByVal SolicitudServicioRecepcion As ServiceRefFEstandar.solicitudRecepcion) As ServiceRefFEstandar.respuesta
            Dim inValue As ServiceRefFEstandar.recepcionPaqueteFacturaElectronicaEstandar = New ServiceRefFEstandar.recepcionPaqueteFacturaElectronicaEstandar()
            inValue.SolicitudServicioRecepcion = SolicitudServicioRecepcion
            Dim retVal As ServiceRefFEstandar.recepcionPaqueteFacturaElectronicaEstandarResponse = CType(Me, ServiceRefFEstandar.IServicioFacturaElectronicaEstandar).recepcionPaqueteFacturaElectronicaEstandar(inValue)
            Return retVal.RespuestaServicioFacturacion
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ServiceRefFEstandar_IServicioFacturaElectronicaEstandar_verificarComunicacion(ByVal request As ServiceRefFEstandar.verificarComunicacion) As ServiceRefFEstandar.verificarComunicacionResponse Implements ServiceRefFEstandar.IServicioFacturaElectronicaEstandar.verificarComunicacion
            Return MyBase.Channel.verificarComunicacion(request)
        End Function

        Public Function verificarComunicacion() As Integer
            Dim inValue As ServiceRefFEstandar.verificarComunicacion = New ServiceRefFEstandar.verificarComunicacion()
            Dim retVal As ServiceRefFEstandar.verificarComunicacionResponse = CType(Me, ServiceRefFEstandar.IServicioFacturaElectronicaEstandar).verificarComunicacion(inValue)
            Return retVal.[return]
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ServiceRefFEstandar_IServicioFacturaElectronicaEstandar_validacionAnulacionFacturaElectronicaEstandar(ByVal request As ServiceRefFEstandar.validacionAnulacionFacturaElectronicaEstandar) As ServiceRefFEstandar.validacionAnulacionFacturaElectronicaEstandarResponse Implements ServiceRefFEstandar.IServicioFacturaElectronicaEstandar.validacionAnulacionFacturaElectronicaEstandar
            Return MyBase.Channel.validacionAnulacionFacturaElectronicaEstandar(request)
        End Function

        Public Function validacionAnulacionFacturaElectronicaEstandar(ByVal SolicitudServicioValidacionAnulacion As ServiceRefFEstandar.solicitudValidacionAnulacion) As ServiceRefFEstandar.respuesta
            Dim inValue As ServiceRefFEstandar.validacionAnulacionFacturaElectronicaEstandar = New ServiceRefFEstandar.validacionAnulacionFacturaElectronicaEstandar()
            inValue.SolicitudServicioValidacionAnulacion = SolicitudServicioValidacionAnulacion
            Dim retVal As ServiceRefFEstandar.validacionAnulacionFacturaElectronicaEstandarResponse = CType(Me, ServiceRefFEstandar.IServicioFacturaElectronicaEstandar).validacionAnulacionFacturaElectronicaEstandar(inValue)
            Return retVal.RespuestaServicioFacturacion
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ServiceRefFEstandar_IServicioFacturaElectronicaEstandar_validacionRecepcionFacturaElectronicaEstandar(ByVal request As ServiceRefFEstandar.validacionRecepcionFacturaElectronicaEstandar) As ServiceRefFEstandar.validacionRecepcionFacturaElectronicaEstandarResponse Implements ServiceRefFEstandar.IServicioFacturaElectronicaEstandar.validacionRecepcionFacturaElectronicaEstandar
            Return MyBase.Channel.validacionRecepcionFacturaElectronicaEstandar(request)
        End Function

        Public Function validacionRecepcionFacturaElectronicaEstandar(ByVal SolicitudServicioValidacionRecepcion As ServiceRefFEstandar.solicitudValidacionRecepcion) As ServiceRefFEstandar.respuesta
            Dim inValue As ServiceRefFEstandar.validacionRecepcionFacturaElectronicaEstandar = New ServiceRefFEstandar.validacionRecepcionFacturaElectronicaEstandar()
            inValue.SolicitudServicioValidacionRecepcion = SolicitudServicioValidacionRecepcion
            Dim retVal As ServiceRefFEstandar.validacionRecepcionFacturaElectronicaEstandarResponse = CType(Me, ServiceRefFEstandar.IServicioFacturaElectronicaEstandar).validacionRecepcionFacturaElectronicaEstandar(inValue)
            Return retVal.RespuestaServicioFacturacion
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ServiceRefFEstandar_IServicioFacturaElectronicaEstandar_recepcionFacturaElectronicaEstandar(ByVal request As ServiceRefFEstandar.recepcionFacturaElectronicaEstandar) As ServiceRefFEstandar.recepcionFacturaElectronicaEstandarResponse Implements ServiceRefFEstandar.IServicioFacturaElectronicaEstandar.recepcionFacturaElectronicaEstandar
            Return MyBase.Channel.recepcionFacturaElectronicaEstandar(request)
        End Function

        Public Function recepcionFacturaElectronicaEstandar(ByVal SolicitudServicioRecepcion As ServiceRefFEstandar.solicitudRecepcion) As ServiceRefFEstandar.respuesta
            Dim inValue As ServiceRefFEstandar.recepcionFacturaElectronicaEstandar = New ServiceRefFEstandar.recepcionFacturaElectronicaEstandar()
            inValue.SolicitudServicioRecepcion = SolicitudServicioRecepcion
            Dim retVal As ServiceRefFEstandar.recepcionFacturaElectronicaEstandarResponse = CType(Me, ServiceRefFEstandar.IServicioFacturaElectronicaEstandar).recepcionFacturaElectronicaEstandar(inValue)
            Return retVal.RespuestaServicioFacturacion
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ServiceRefFEstandar_IServicioFacturaElectronicaEstandar_anulacionFacturaElectronicaEstandar(ByVal request As ServiceRefFEstandar.anulacionFacturaElectronicaEstandar) As ServiceRefFEstandar.anulacionFacturaElectronicaEstandarResponse Implements ServiceRefFEstandar.IServicioFacturaElectronicaEstandar.anulacionFacturaElectronicaEstandar
            Return MyBase.Channel.anulacionFacturaElectronicaEstandar(request)
        End Function

        Public Function anulacionFacturaElectronicaEstandar(ByVal SolicitudServicioAnulacion As ServiceRefFEstandar.solicitudAnulacion) As ServiceRefFEstandar.respuesta
            Dim inValue As ServiceRefFEstandar.anulacionFacturaElectronicaEstandar = New ServiceRefFEstandar.anulacionFacturaElectronicaEstandar()
            inValue.SolicitudServicioAnulacion = SolicitudServicioAnulacion
            Dim retVal As ServiceRefFEstandar.anulacionFacturaElectronicaEstandarResponse = CType(Me, ServiceRefFEstandar.IServicioFacturaElectronicaEstandar).anulacionFacturaElectronicaEstandar(inValue)
            Return retVal.RespuestaServicioFacturacion
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ServiceRefFEstandar_IServicioFacturaElectronicaEstandar_validacionRecepcionPaqueteFacturaElectronicaEstandar(ByVal request As ServiceRefFEstandar.validacionRecepcionPaqueteFacturaElectronicaEstandar) As ServiceRefFEstandar.validacionRecepcionPaqueteFacturaElectronicaEstandarResponse Implements ServiceRefFEstandar.IServicioFacturaElectronicaEstandar.validacionRecepcionPaqueteFacturaElectronicaEstandar
            Return MyBase.Channel.validacionRecepcionPaqueteFacturaElectronicaEstandar(request)
        End Function

        Public Function validacionRecepcionPaqueteFacturaElectronicaEstandar(ByVal SolicitudServicioValidacionRecepcion As ServiceRefFEstandar.solicitudValidacionRecepcion) As ServiceRefFEstandar.respuesta
            Dim inValue As ServiceRefFEstandar.validacionRecepcionPaqueteFacturaElectronicaEstandar = New ServiceRefFEstandar.validacionRecepcionPaqueteFacturaElectronicaEstandar()
            inValue.SolicitudServicioValidacionRecepcion = SolicitudServicioValidacionRecepcion
            Dim retVal As ServiceRefFEstandar.validacionRecepcionPaqueteFacturaElectronicaEstandarResponse = CType(Me, ServiceRefFEstandar.IServicioFacturaElectronicaEstandar).validacionRecepcionPaqueteFacturaElectronicaEstandar(inValue)
            Return retVal.RespuestaServicioFacturacion
        End Function
    End Class
End Namespace
