'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.1.
'

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class facturaElectronicaComercialExportacion
    
    Private cabeceraField As facturaElectronicaComercialExportacionCabecera
    
    Private detalleField() As facturaElectronicaComercialExportacionDetalle
    
    '''<comentarios/>
    Public Property cabecera() As facturaElectronicaComercialExportacionCabecera
        Get
            Return Me.cabeceraField
        End Get
        Set
            Me.cabeceraField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("detalle")>  _
    Public Property detalle() As facturaElectronicaComercialExportacionDetalle()
        Get
            Return Me.detalleField
        End Get
        Set
            Me.detalleField = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class facturaElectronicaComercialExportacionCabecera
    
    Private nitEmisorField As String
    
    Private numeroFacturaField As String
    
    Private cufField As String
    
    Private cufdField As String
    
    Private codigoSucursalField As String
    
    Private direccionField As String
    
    Private codigoPuntoVentaField As String
    
    Private fechaEmisionField As Date
    
    Private nombreRazonSocialField As String
    
    Private codigoTipoDocumentoIdentidadField As String
    
    Private numeroDocumentoField As String
    
    Private complementoField As String
    
    Private direccionCompradorField As String
    
    Private codigoClienteField As String
    
    Private incotermField As String
    
    Private puertoDestinoField As String
    
    Private lugarDestinoField As String
    
    Private codigoPaisField As String
    
    Private codigoMetodoPagoField As String
    
    Private numeroTarjetaField As String
    
    Private montoTotalField As Decimal
    
    Private montoTotalPuertoField As Decimal
    
    Private precioValorBrutoField As Decimal
    
    Private gastosTransporteFronteraField As Decimal
    
    Private gastosSeguroFronteraField As Decimal
    
    Private totalFobFronteraField As Decimal
    
    Private montoTransporteFronteraField As Decimal
    
    Private montoSeguroInternacionalField As Decimal
    
    Private otrosMontosField As System.Nullable(Of Decimal)
    
    Private montoDescuentoField As System.Nullable(Of Decimal)
    
    Private codigoMonedaField As String
    
    Private tipoCambioField As Decimal
    
    Private montoTotalMonedaField As Decimal
    
    Private leyendaField As String
    
    Private usuarioField As String
    
    Private codigoDocumentoSectorField As String
    
    Public Sub New()
        MyBase.New
        Me.codigoDocumentoSectorField = "12"
    End Sub
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
    Public Property nitEmisor() As String
        Get
            Return Me.nitEmisorField
        End Get
        Set
            Me.nitEmisorField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
    Public Property numeroFactura() As String
        Get
            Return Me.numeroFacturaField
        End Get
        Set
            Me.numeroFacturaField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property cuf() As String
        Get
            Return Me.cufField
        End Get
        Set
            Me.cufField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property cufd() As String
        Get
            Return Me.cufdField
        End Get
        Set
            Me.cufdField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
    Public Property codigoSucursal() As String
        Get
            Return Me.codigoSucursalField
        End Get
        Set
            Me.codigoSucursalField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property direccion() As String
        Get
            Return Me.direccionField
        End Get
        Set
            Me.direccionField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", IsNullable:=true)>  _
    Public Property codigoPuntoVenta() As String
        Get
            Return Me.codigoPuntoVentaField
        End Get
        Set
            Me.codigoPuntoVentaField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property fechaEmision() As Date
        Get
            Return Me.fechaEmisionField
        End Get
        Set
            Me.fechaEmisionField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property nombreRazonSocial() As String
        Get
            Return Me.nombreRazonSocialField
        End Get
        Set
            Me.nombreRazonSocialField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
    Public Property codigoTipoDocumentoIdentidad() As String
        Get
            Return Me.codigoTipoDocumentoIdentidadField
        End Get
        Set
            Me.codigoTipoDocumentoIdentidadField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property numeroDocumento() As String
        Get
            Return Me.numeroDocumentoField
        End Get
        Set
            Me.numeroDocumentoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Property complemento() As String
        Get
            Return Me.complementoField
        End Get
        Set
            Me.complementoField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property direccionComprador() As String
        Get
            Return Me.direccionCompradorField
        End Get
        Set
            Me.direccionCompradorField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property codigoCliente() As String
        Get
            Return Me.codigoClienteField
        End Get
        Set
            Me.codigoClienteField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property incoterm() As String
        Get
            Return Me.incotermField
        End Get
        Set
            Me.incotermField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property puertoDestino() As String
        Get
            Return Me.puertoDestinoField
        End Get
        Set
            Me.puertoDestinoField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property lugarDestino() As String
        Get
            Return Me.lugarDestinoField
        End Get
        Set
            Me.lugarDestinoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
    Public Property codigoPais() As String
        Get
            Return Me.codigoPaisField
        End Get
        Set
            Me.codigoPaisField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
    Public Property codigoMetodoPago() As String
        Get
            Return Me.codigoMetodoPagoField
        End Get
        Set
            Me.codigoMetodoPagoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", IsNullable:=true)>  _
    Public Property numeroTarjeta() As String
        Get
            Return Me.numeroTarjetaField
        End Get
        Set
            Me.numeroTarjetaField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property montoTotal() As Decimal
        Get
            Return Me.montoTotalField
        End Get
        Set
            Me.montoTotalField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property montoTotalPuerto() As Decimal
        Get
            Return Me.montoTotalPuertoField
        End Get
        Set
            Me.montoTotalPuertoField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property precioValorBruto() As Decimal
        Get
            Return Me.precioValorBrutoField
        End Get
        Set
            Me.precioValorBrutoField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property gastosTransporteFrontera() As Decimal
        Get
            Return Me.gastosTransporteFronteraField
        End Get
        Set
            Me.gastosTransporteFronteraField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property gastosSeguroFrontera() As Decimal
        Get
            Return Me.gastosSeguroFronteraField
        End Get
        Set
            Me.gastosSeguroFronteraField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property totalFobFrontera() As Decimal
        Get
            Return Me.totalFobFronteraField
        End Get
        Set
            Me.totalFobFronteraField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property montoTransporteFrontera() As Decimal
        Get
            Return Me.montoTransporteFronteraField
        End Get
        Set
            Me.montoTransporteFronteraField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property montoSeguroInternacional() As Decimal
        Get
            Return Me.montoSeguroInternacionalField
        End Get
        Set
            Me.montoSeguroInternacionalField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Property otrosMontos() As System.Nullable(Of Decimal)
        Get
            Return Me.otrosMontosField
        End Get
        Set
            Me.otrosMontosField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Property montoDescuento() As System.Nullable(Of Decimal)
        Get
            Return Me.montoDescuentoField
        End Get
        Set
            Me.montoDescuentoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
    Public Property codigoMoneda() As String
        Get
            Return Me.codigoMonedaField
        End Get
        Set
            Me.codigoMonedaField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property tipoCambio() As Decimal
        Get
            Return Me.tipoCambioField
        End Get
        Set
            Me.tipoCambioField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property montoTotalMoneda() As Decimal
        Get
            Return Me.montoTotalMonedaField
        End Get
        Set
            Me.montoTotalMonedaField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property leyenda() As String
        Get
            Return Me.leyendaField
        End Get
        Set
            Me.leyendaField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property usuario() As String
        Get
            Return Me.usuarioField
        End Get
        Set
            Me.usuarioField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
    Public Property codigoDocumentoSector() As String
        Get
            Return Me.codigoDocumentoSectorField
        End Get
        Set
            Me.codigoDocumentoSectorField = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class facturaElectronicaComercialExportacionDetalle
    
    Private actividadEconomicaField As Long
    
    Private codigoProductoSinField As String
    
    Private codigoProductoField As String
    
    Private codigoNandinaField As String
    
    Private descripcionField As String
    
    Private cantidadField As Decimal
    
    Private unidadMedidaField As String
    
    Private precioUnitarioField As Decimal
    
    Private montoDescuentoField As System.Nullable(Of Decimal)
    
    Private subTotalField As Decimal
    
    '''<comentarios/>
    Public Property actividadEconomica() As Long
        Get
            Return Me.actividadEconomicaField
        End Get
        Set
            Me.actividadEconomicaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
    Public Property codigoProductoSin() As String
        Get
            Return Me.codigoProductoSinField
        End Get
        Set
            Me.codigoProductoSinField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property codigoProducto() As String
        Get
            Return Me.codigoProductoField
        End Get
        Set
            Me.codigoProductoField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property codigoNandina() As String
        Get
            Return Me.codigoNandinaField
        End Get
        Set
            Me.codigoNandinaField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property descripcion() As String
        Get
            Return Me.descripcionField
        End Get
        Set
            Me.descripcionField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property cantidad() As Decimal
        Get
            Return Me.cantidadField
        End Get
        Set
            Me.cantidadField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
    Public Property unidadMedida() As String
        Get
            Return Me.unidadMedidaField
        End Get
        Set
            Me.unidadMedidaField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property precioUnitario() As Decimal
        Get
            Return Me.precioUnitarioField
        End Get
        Set
            Me.precioUnitarioField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Property montoDescuento() As System.Nullable(Of Decimal)
        Get
            Return Me.montoDescuentoField
        End Get
        Set
            Me.montoDescuentoField = value
        End Set
    End Property
    
    '''<comentarios/>
    Public Property subTotal() As Decimal
        Get
            Return Me.subTotalField
        End Get
        Set
            Me.subTotalField = value
        End Set
    End Property
End Class
